### PR TITLE
Support jsdoc link types and settings

### LINKED ISSUE #85: Add support for `{@linkcode}`, `{linkplain}` tags and  clever links, monospace links options
The standard jsdoc spec defnies support for monospace and plain text link formatting which is currently missing from jsdoc-to-markdown. (See [jsdoc `{@link}` page](https://jsdoc.app/tags-inline-link).)

To match the jsdoc links, let's add `{@linkcode}` (which are rendered in monospace) and `{@linkplain}` (which are rendered in plain text) tags as well as 'clever links' and 'monospace links' options. When 'clever links' is true, then links are rendered in monospace unless the link target is a URL (e.g., links to functions, modules, classes, etc. are rendered in monospace). When 'monospace links' is true, then `{@link}` tags are rendered in monospace. The 'monospace links' options is ignored if 'clever links' is true.

Support for setting the options from the command line is proposed in [jsdoc-to-markdown#301](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/301).

### PR DESCRIPTION
**Pull request by zanerock**
Updates link processing logic to adds support for jsdoc style `{@linkplain}` and `{@linkcode}` tags as well as `DmdOptions['clever-links']` and `DmdOptions['monospace-links']` options per jsdoc specification. Also updates tests and function documentation.

See also [jsdoc-to-markdown pull request #302](https://github.com/jsdoc2md/jsdoc-to-markdown/pull/302).

Closes #85

### CODE REVIEW

**Comment by 75lb** [comment]
PR looks pretty complete, thanks.. will look into it..

**Comment by 75lb** [comment]
I merged this PR locally and had a play with it.. Could you check the `0-src.js` (source) and `3-dmd.md` (dmd output) files in these two folders and confirm whether they look correct or not? 

* https://github.com/jsdoc2md/testbed/tree/master/build/jsdoc/global/clever-links
* https://github.com/jsdoc2md/testbed/tree/master/build/jsdoc/global/monospace-links

Cheers!

**Comment by zanerock** [comment]
Good idea with the examples. It looks correct to me. With '--clever-links', `{@link ...}` renders the URL plain and the code ref in monospace. And with '--monospace-links', `{@link ...}` renders monospace in both cases. (And `{@linkplain ...}` and `{@linkcode ...}` behave as advertised.

**Comment by 75lb** [comment]
Merged, see https://github.com/jsdoc2md/jsdoc-to-markdown/issues/301

**Pull request closed without merging**
