### PR TITLE
Add typeLinks helper and wrap link inside linked-type-list.hbs

### PR DESCRIPTION
**Pull request by plasticrake**
I took a stab at implementing this: jsdoc2md/jsdoc-to-markdown#138

I have almost no experience with handlebars besides what I had to learn to implement this. So I'm not sure if I did it in the right place. I tried to wrap the existing code instead of modifying.

Currently For: `Name.<Name2>` only `Name2 `will become a link

Will create links for the following formats (each Name will be a link):
`Name.<Name2>`
`Name.<Name2, Name3>`
`Name.<Name2, Name3, Name4>`...etc

### CODE REVIEW

**Comment by 75lb** [comment]
hi, sorry for the slow response! Thanks for this patch, will get round to testing it asap. Are you using it locally?

**Comment by plasticrake** [comment]
Yes! I have been using this locally.

**Comment by 75lb** [comment]
Unfortunately this breaks some cases. Please fix the PR so this code:

```js
/**
 * @type {module:cjs/human[]}
 */
var returnsArrayOfType

/**
 * @type {?module:cjs/human[]}
 */
var returnsArrayOfType2
```

...returns this markup, as it did before this PR: 

```md
<a name="returnsArrayOfType"></a>

## returnsArrayOfType : <code>Array.&lt;module:cjs/human&gt;</code>
**Kind**: global variable  
<a name="returnsArrayOfType2"></a>

## returnsArrayOfType2 : <code>Array.&lt;module:cjs/human&gt;</code>
**Kind**: global variable  
```

**Comment by 75lb** [comment]
Closing as stale and incomplete

**Pull request closed without merging**
